### ISSUE TITLE
Does the timeline control have to go in a corner?

### ISSUE THREAD

**Issue by jbielski** [svitkin/leaflet-timeline-slider#4]
I'd prefer to have my timeline centered and along the bottom of my map. Is that possible?

**Comment by svitkin** [comment]
As far as I know, leaflet does not have a 'center' option for its custom controls. For this particular control though, you can get what you want with a slightly hacky solution. Assuming you have jquery, this should work to identify the timeline and change its position:

`$('#rangeinputslide').parent('.range').parent('.leaflet-control').css('left', '-70%')`

I put 70% in because that's what looked good for me, but I would just mess around with that until you get something that looks good.

**Comment by jbielski** [comment]
I used $('#rangeinputslide').parent('.range').parent('.leaflet-control').css('right', '90%') to get it horizontally where I wanted. Now I just have to figure out how to put it a little lower on the screen.

**Comment by svitkin** [comment]
I would just try the same thing as another line of code after, but with `.css('top', 'xx%')` at the end to control the vertical positioning of the timeline. The properties `'top', 'bottom', 'left', 'right'` are all css properties that control the positioning of an element so I would just mess around with those until you get something that fits your needs. The first part of the code before the css styling just finds the timeline element. I'm going to close this issue. Feel free to open it back up if my advice did not work.
